### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by ManyHatsOfLinux** [Hunter522/mumpi#2]
`
`

`root@computerroom:~/mumpi-master/build#` cmake ..
CMake Error at CMakeLists.txt:8 (add_subdirectory):
  The source directory

    /root/mumpi-master/deps/mumlib

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:36 (add_subdirectory):
  The source directory

    /root/mumpi-master/deps/googletest

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/root/mumpi-master/build/CMakeFiles/CMakeOutput.log".
root@computerroom:~/mumpi-master/build#

``

**Comment by auzanmuh** [comment]
because you haven't meet all dependencies. 
`git submodule init && git submodule update`
to clone googletest repository and mumlib

**Comment by ManyHatsOfLinux** [comment]
Thank you very much. This was a failure on my part. Will Fix on my own accord. Would you like me to close the issue?
